# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=500, primary_key=True, serialize=False, verbose_name='Наименование')),
                ('page_count', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('author', models.CharField(max_length=700, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
